"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const prompt_sync_1 = __importDefault(require("prompt-sync"));
const random_js_1 = require("random-js");
const prompt = (0, prompt_sync_1.default)();
const random = new random_js_1.Random();
do {
    let x = parseInt(prompt('Enter a number between 1 and 5:'));
    if (x < 1 || x > 5) {
        let x = parseInt(prompt('The number should be between 1 and 5:'));
    }
    else {
        let y = random.integer(1, 5);
        console.log(`The number you have selected is: ${x}`);
        console.log(`The number generated by the machine is: ${y}`);
        if (x === y) {
            console.log("Congrats, you have guessed right");
        }
        else {
            console.log("Sorry, your wrong. Please try again.");
        }
    }
    var z = prompt('Do you wish to continue(Enter yes or no): ');
} while (z == 'Yes' || z == 'yes' || z == 'y');
