
import PromptSync from "prompt-sync";
import { Random } from "random-js";

const prompt = PromptSync();
const random = new Random();

do {

let x : number = parseInt(prompt('Enter a number between 1 and 5:'));

if (x < 1  || x > 5) {
    let x : number = parseInt(prompt('The number should be between 1 and 5:'));
} else {




let y : number = random.integer(1, 5)

console.log(`The number you have selected is: ${x}`)

console.log(`The number generated by the machine is: ${y}`)

if ( x === y) {
    console.log("Congrats, you have guessed right")
}  else {
    console.log("Sorry, your wrong. Please try again.")
}
}

var z : string = prompt('Do you wish to continue(Enter yes or no): ') 
} while (
    z == 'Yes' || z== 'yes' || z == 'y' 
)







